name: CI/CD Pipeline - Fusionpact DevOps Assessment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Debug GitHub Secrets (username only)
      - name: Check DockerHub username secret
        run: |
          echo "DockerHub username is: ${{ secrets.DOCKERHUB_USERNAME }}"

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Log in to Docker Hub (stable v2 action)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 5: Build Backend Image
      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest ./backend

      # Step 6: Build Frontend Image
      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./frontend

      # Step 7: Run Backend Tests (optional)
      - name: Run Backend Tests
        working-directory: ./backend
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -d tests ]; then pytest || echo "No tests found"; fi

      # Step 8: Push Docker Images
      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      # Step 9: Deploy to Azure VM via SSH
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/azureuser/fusionpact
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            sudo docker-compose down || true
            sudo docker-compose up -d --remove-orphans
            echo "✅ Deployment successful"
